# Test on macOS M1 silicon
#
# cibuildwheel FAQ helps (search "cirrus"):
# https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon
# https://cirrus-ci.org/guide/writing-tasks/#supported-instructions
# In commit messages, [skip ci] or [skip cirrus] is supported natively.
macos_arm64_task:
  name: macOS arm64 (M1) tests
  # Auto-cancel PR builds
  auto_cancellation: $CIRRUS_PR != ''
  only_if: $CIRRUS_REPO_FULL_NAME == "mne-tools/mne-python"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  env:
    PATH: /opt/homebrew/opt/python@3.10/libexec/bin:$PATH
  python_install_script:
    - ./tools/cirrus_install_python.sh
  pip_cache:
    folder: ~/Library/Caches/pip
    fingerprint_script:
      - echo $PYTHON_VERSION && cat requirements.txt && cat requirements_testing.txt && cat requirements_testing_extra.txt
    populate_script:
      - ./tools/cirrus_dependencies.sh
  pip_install_script:  # now we actually run it (possibly another time) to install deps
    - ./tools/cirrus_dependencies.sh
  mne_install_script:
    - pip install -ve .
  mne_sys_info_script:
    - mne sys_info -pd
  testing_cache:
    folder: ~/mne_data
    fingerprint_script:
      - ./tools/get_testing_version.sh
    populate_script:
      - python -c "import mne; mne.datasets.testing.data_path(force_update=True, verbose=True)"
  pytest_script:
    - pytest -m "not slowtest" --tb=short --cov=mne --cov-report=xml -vv mne
  # https://cirrus-ci.org/guide/writing-tasks/#artifact-parsing
  always:
    upload_results_artifacts:
      path: ./*.xml
      format: junit
      type: text/xml
    codecov_script: bash <(curl -s https://codecov.io/bash)
