name: mne-dev-py36
channels:
- defaults
dependencies:
- python=3.6
- cython
- flake8
- h5py
- ipython
- joblib
- jupyter
- matplotlib
- mkl
- numexpr
- numpy
- numpydoc
- pandas
- pillow
- pip
- psutil
- pyface>=6
- pyqt>=5.9
- pytest
- pytest-cov
- scikit-learn
- scipy
- sphinx
- spyder
- statsmodels
- testpath<0.4
- traits>=4.6.0
- traitsui>=6
- vtk>=8
- pip:
  - PySurfer[save_movie]
  - codespell
  - dipy
  - https://api.github.com/repos/enthought/mayavi/zipball/b3fc35218dda9776d8f1a407663bfb49783dca12
  - https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master
  - neo
  - nibabel
  - nilearn
  - nitime
  - pydocstyle
  - pytest-faulthandler
  - python-picard
  - sphinx_bootstrap_theme
  - sphinx_fontawesome

