name: mne
channels:
- conda-forge
dependencies:
- python>=3.5
- pip
- numpy
- scipy
- matplotlib-base
- numba
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numpydoc>=1.0
- numexpr
- pyqt>=5.10,<5.14
- traits>=4.6.0
# FIXME - pyface>=6
- traitsui>=6
- imageio>=2.6.1
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.24
- pyvistaqt
- nibabel
- nilearn
- python-picard
- tqdm
- python-neo
- dipy
# FIXME - pysurfer
# For unit testing
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- pytest-xdist
- pytest-sugar
- pydocstyle
- codespell
- flake8
- pip:
  - mne
  # - https://github.com/enthought/mayavi/archive/master.zip
