[workspace]
authors = ["MNE-Python contributors"]
channels = ["conda-forge"]
name = "mne"
platforms = ["osx-64"]
version = "0.1.0"

[dependencies]
antio = ">=0.5.0"
codespell = "*"
curryreader = ">=0.1.2"
darkdetect = "*"
decorator = ">=5.1"
defusedxml = "*"
dipy = ">=0.8"
edfio = ">=0.4.10"
eeglabio = "*"
filelock = ">=3.18.0"
h5io = ">=0.2.4"
h5py = ">=2.4"
imageio = ">=2.6.1"
imageio-ffmpeg = ">=0.4.1"
ipyevents = "*"
ipympl = "*"
ipython = ">=8.20"
ipywidgets = "*"
jinja2 = ">=3.1"
joblib = ">=0.8"
jupyter = "*"
jupyter_client = "*"
lazy_loader = ">=0.3"
matplotlib = ">=3.9"
mffpy = ">=0.11.0"
mne-qt-browser = "*"
mypy = ">=0.14"
nbclient = "*"
nest-asyncio2 = "*"
nibabel = ">=2.0"
nilearn = "*"
nitime = ">=0.7"
numba = ">=0.35"
numpy = ">=2.0,<3"
numpydoc = ">=1.6"
openmeeg = ">=2.5.7"
packaging = "*"
pandas = ">=2.2,!=3.0.4"
pillow = ">=10.2"
pip = ">=25.1"
pooch = ">=1.5"
pre-commit = "*"
pyarrow = "*"
pybv = "*"
pymatreader = "*"
pyobjc-framework-Cocoa = ">=5.2.0"
pyside6 = ">=6.11.1"
pytest = ">=8.0,!=9.1.0"
pytest-cov = ">=4.1"
pytest-qt = ">=4.3"
pytest-rerunfailures = "*"
pytest-timeout = ">=2.2"
python = "3.13.*"
python-neo = "*"
python-picard = ">=0.4"
pyvista = ">=0.43"
pyvistaqt = ">=0.11"
qdarkstyle = "!=3.2.2"
qtpy = "*"
rcssmin = ">=1.1"
refleak = "*"
ruff = ">=0.1"
scikit-learn = ">=1.5"
scipy = ">=1.14"
sip = "*"
snirf = "*"
statsmodels = ">=0.6"
threadpoolctl = "*"
tqdm = ">=4.66"
traitlets = "*"
trame = "*"
trame-pyvista = "*"
trame-vtk = "*"
trame-vuetify = "*"
twine = "*"
vtk = ">=9.2"
vulture = "*"
xlrd = "*"

[pypi-dependencies]
pymef = "*"
