#!/usr/bin/env python

# Authors: The MNE-Python contributors.
# License: BSD-3-Clause
# Copyright the MNE-Python contributors.

import difflib
import re
from pathlib import Path

import tomllib

repo_root = Path(__file__).resolve().parents[2]
pyproj = tomllib.loads((repo_root / "pyproject.toml").read_text("utf-8"))

# Get our "full" dependences from `pyproject.toml`, but actually ignore the
# "full" section as it's just "full-noqt" plus PyQt6, and for conda we need PySide
ignore = ("dev", "doc", "test", "test_extra", "full", "full-pyqt6")
deps = set(pyproj["project"]["dependencies"])
for section, section_deps in pyproj["project"]["optional-dependencies"].items():
    if section not in ignore:
        deps |= set(section_deps)
recursive_deps = set(d for d in deps if d.startswith("mne["))
deps -= recursive_deps
deps |= {"pip"}


def remove_spaces(version_spec):
    """Remove spaces in version specs (conda is stricter than pip about this).

    https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications
    """
    return "".join(version_spec.split())


def split_dep(dep):
    """Separate package name from version spec."""
    pattern = re.compile(r"([^!=<>]+)?([!=<>].*)?")
    groups = list(pattern.match(dep).groups())
    groups[1] = "" if groups[1] is None else remove_spaces(groups[1])
    return tuple(map(str.strip, groups))


# python version
req_python = remove_spaces(pyproj["project"]["requires-python"])

# split package name from version spec
translations = dict(neo="python-neo")
pip_deps = set()
conda_deps = set()
check_old = (
    "numpy scipy matplotlib pandas scikit-learn nibabel tqdm pooch decorator "
    "packaging jinja2 lazy_loader"
).split()
old_deps = [None] * len(check_old)
for dep in deps:
    package_name, version_spec = split_dep(dep)
    # handle package name differences
    package_name = translations.get(package_name, package_name)
    # PySide6==6.7.0 only exists on PyPI, not conda-forge, so excluding it in
    # `environment.yaml` breaks the solver
    if package_name == "PySide6":
        version_spec = "<6.8.0"
    elif package_name == "scipy":
        version_spec = f"{version_spec},<1.15.0"
    # rstrip output line in case `version_spec` == ""
    line = f"  - {package_name} {version_spec}".rstrip()
    # use pip for packages needing e.g. `platform_system` or `python_version` triaging
    if ";" in version_spec:
        pip_deps.add(f"    {line}")
    else:
        conda_deps.add(line)
    # old deps
    if package_name in check_old:
        # Pull out >= part, change to =, remove < (which should be after comma)
        old_deps[check_old.index(package_name)] = line.replace(">=", "=").split(",")[0]
for di, dep in enumerate(old_deps):
    assert dep is not None, f"Missing {check_old[di]}"

# TODO: temporary workaround while we wait for a release containing the fix for
# https://github.com/mamba-org/mamba/issues/3467
pip_deps.remove("      - pyobjc-framework-Cocoa >=5.2.0;platform_system=='Darwin'")

# prepare the pip dependencies section
newline = "\n"  # python < 3.12 forbids backslash in {} part of f-string
pip_section = f"""\
  - pip:
{newline.join(sorted(pip_deps, key=str.casefold))}
"""
pip_section = pip_section if len(pip_deps) else ""
# prepare the env file
header = f"""\
# THIS FILE IS AUTO-GENERATED BY {'/'.join(Path(__file__).parts[-3:])} AND WILL BE OVERWRITTEN
name: mne
channels:
  - conda-forge
dependencies:"""  # noqa: E501
env = f"""{header}
  - python {req_python}
{newline.join(sorted(conda_deps, key=str.casefold))}
{pip_section}"""

env_file = repo_root / "environment.yml"
old_env = env_file.read_text("utf-8")
if old_env != env:
    diff = "\n".join(difflib.unified_diff(old_env.splitlines(), env.splitlines()))
    print(f"Updating {env_file} with diff:\n{diff}")
    env_file.write_text(env, encoding="utf-8")

# Now we also updated tools/environment_old.yml
env_file = repo_root / "tools" / "environment_old.yml"
old_env = env_file.read_text("utf-8")
use_python = req_python.replace(">=", "=")
env = f"""{header}
  - python {use_python}
{newline.join(old_deps)}
"""
if old_env != env:
    diff = "\n".join(difflib.unified_diff(old_env.splitlines(), env.splitlines()))
    print(f"Updating {env_file} with diff:\n{diff}")
    env_file.write_text(env, encoding="utf-8")
