blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/mne-tools/mne-python/discussions
    about: Ask questions, share ideas, engage with the MNE-Python community.
  - name: Mailing list
    url: http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis
    about: For questions about analysis and usage, and announcements of interest to the neuroimaging community.
  - name: Gitter
    url: https://gitter.im/mne-tools/mne-python
    about: Users and developers can chat, troubleshoot, and share code samples on our Gitter channel.
