blank_issues_enabled: true
contact_links:
  - name: 💬 MNE-Python forum
    url: https://mne.discourse.group/
    about: Ask (and answer) concrete technical questions or usage questions about MNE-Python on the forum