blank_issues_enabled: false
contact_links:
  - name: Questions/Support/Other
    url: https://github.com/mne-tools/mne-python/discussions
    about: Get help using MNE-Python, ask general (usage) questions, or share your ideas with the community.
