#! /usr/bin/env python

import os
import sys

args = sys.argv

if '-h' in args:
    print "build_doc [--nocfg] [--nosphinx] [--noweb]"
    sys.exit(0)

if "--nosphinx" not in args:
    os.system("make html")

# if "--noweb" not in args:
#     os.system("scp -r build/html/* user@ftp.XXX.edu:pyfiff")
