.. raw:: html

    <div id="examples_carousel" class="carousel slide" data-ride="carousel">
        <ol id="mne_index_indicators" class="carousel-indicators">
            <li data-target="#examples_carousel" data-slide-to="0" class="active"></li>
            <li data-target="#examples_carousel" data-slide-to="1" class=""></li>
            <li data-target="#examples_carousel" data-slide-to="2" class=""></li>
            <li data-target="#examples_carousel" data-slide-to="3" class=""></li>
            <li data-target="#examples_carousel" data-slide-to="4" class=""></li>
            <li data-target="#examples_carousel" data-slide-to="5" class=""></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="carousel-item active">
              <a href="auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_mne_dspm_source_localization_008.gif)" title="dSPM">
                    <div class="carousel-caption">
                        <h3>Source estimation</h3>
                        <p>Distributed, sparse, mixed-norm, beamformers, dipole fitting, and more.</p>
                    </div>
                </div>
              </a>
            </div>


            <div class="carousel-item">
              <a href="auto_tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_stats_cluster_spatio_temporal_001.png)" title="Clusters">
                    <div class="carousel-caption">
                        <h3>Statistics</h3>
                        <p>Parametric and non-parametric, permutation tests and clustering.</p>
                    </div>
                </div>
              </a>
            </div>

            <div class="carousel-item">
              <a href="auto_tutorials/machine-learning/plot_sensors_decoding.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_sensors_decoding_006.png)" title="Decoding">
                    <div class="carousel-caption">
                        <h3>Machine learning</h3>
                        <p>Advanced decoding models including time generalization.</p>
                    </div>
                </div>
              </a>
            </div>

            <div class="carousel-item">
              <a href="auto_tutorials/machine-learning/plot_receptive_field.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_receptive_field_001.png)" title="STRF">
                    <div class="carousel-caption">
                        <h3>Encoding models</h3>
                        <p>Receptive field estimation with optional smoothness priors.</p>
                    </div>
                </div>
              </a>
            </div>

            <div class="carousel-item">
              <a href="auto_examples/connectivity/plot_mne_inverse_label_connectivity.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_mne_inverse_label_connectivity_001.png)" title="Connectivity">
                    <div class="carousel-caption">
                        <h3>Connectivity</h3>
                        <p>All-to-all spectral and effective connectivity measures.</p>
                    </div>
                </div>
              </a>
            </div>

            <div class="carousel-item">
              <a href="auto_tutorials/evoked/plot_20_visualize_evoked.html">
                <div class="chopper" style="background-image: url(_images/sphx_glr_plot_20_visualize_evoked_007.png)" title="Visualization">
                    <div class="carousel-caption">
                        <h3>Data visualization</h3>
                        <p>Explore your data from multiple perspectives.</p>
                    </div>
                </div>
              </a>
            </div>
        </div>

        <!-- Carousel nav -->
        <a class="carousel-control-prev" href="#examples_carousel" role="button" data-slide="prev">
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#examples_carousel" role="button" data-slide="next">
        <span class="sr-only">Next</span>
        </a>
    </div>
