.. raw:: html

    <div id="index_carousel_tn" class="thumbnail nopad">
      <div id="examples_carousel" class="carousel slide nopad" data-ride="carousel">
        <ol id="mne_index_indicators" class="carousel-indicators">
          <li data-target="#examples_carousel" data-slide-to="0" class="active"></li>
          <li data-target="#examples_carousel" data-slide-to="1" class=""></li>
          <li data-target="#examples_carousel" data-slide-to="2" class=""></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
          <div class="item active">
            <div class="chopper container"><img src="_images/_images/sphx_glr_plot_mne_dspm_source_localization_007.png" alt="dSPM" class="carousel-image"></div>
            <div class="container">
              <div class="carousel-caption">
                <p>Source localization.</p>
                <p><a class="btn btn-info btn-xs" href="auto_tutorials/plot_mne_dspm_source_localization.html" role="button">Check it out</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="chopper container"><img src="_images/sphx_glr_plot_receptive_field_0031.png" alt="STRF" class="carousel-image"></div>
            <div class="container">
              <div class="carousel-caption">
                <p>Receptive field estimation.</p>
                <p><a class="btn btn-info btn-xs" href="auto_tutorials/plot_receptive_field.html" role="button">Check it out</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="chopper container"><img src="_images/sphx_glr_plot_mne_inverse_label_connectivity_001.png" alt="Connectivity" class="carousel-image"></div>
            <div class="container">
              <div class="carousel-caption">
                <p>Connectivity.</p>
                <p><a class="btn btn-info btn-xs" href="auto_examples/connectivity/plot_mne_inverse_label_connectivity.html" role="button">Check it out</a></p>
              </div>
            </div>
          </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#examples_carousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="carousel-control right" href="#examples_carousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      </div>
    </div>
