.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. git stuff
.. _git: http://git-scm.com/
.. _github: https://github.com
.. _GitHub Help: https://help.github.com
.. _msysgit: http://code.google.com/p/msysgit/downloads/list
.. _git-osx-installer: http://code.google.com/p/git-osx-installer/downloads/list
.. _subversion: http://subversion.tigris.org/
.. _git cheat sheet: http://github.com/guides/git-cheat-sheet
.. _pro git book: http://progit.org/
.. _git svn crash course: http://git-scm.com/course/svn.html
.. _learn.github: http://learn.github.com/
.. _network graph visualizer: https://github.com/blog/39-say-hello-to-the-network-graph-visualizer
.. _git user manual: https://schacon.github.io/git/user-manual.html
.. _git tutorial: https://schacon.github.io/git/gittutorial.html
.. _git community book: http://book.git-scm.com/
.. _git ready: http://www.gitready.com/
.. _git casts: http://www.gitcasts.com/
.. _Fernando's git page: http://www.fperez.org/py4science/git.html
.. _git magic: http://www-cs-students.stanford.edu/~blynn/gitmagic/index.html
.. _git concepts: http://www.eecs.harvard.edu/~cduan/technical/git/
.. _git clone: http://schacon.github.com/git/git-clone.html
.. _git checkout: https://schacon.github.io/git/git-checkout.html
.. _git commit: https://schacon.github.io/git/git-commit.html
.. _git push: https://schacon.github.io/git/git-push.html
.. _git pull: https://schacon.github.io/git/git-pull.html
.. _git add: https://schacon.github.io/git/git-add.html
.. _git status: https://schacon.github.io/git/git-status.html
.. _git diff: https://schacon.github.io/git/git-diff.html
.. _git log: https://schacon.github.io/git/git-log.html
.. _git branch: https://schacon.github.io/git/git-branch.html
.. _git remote: https://schacon.github.io/git/git-remote.html
.. _git rebase: https://schacon.github.io/git/git-rebase.html
.. _git config: https://schacon.github.io/git/git-config.html
.. _why the -a flag?: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _git staging area: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _tangled working copy problem: http://tomayko.com/writings/the-thing-about-git
.. _git management: http://kerneltrap.org/Linux/Git_Management
.. _linux git workflow: http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _git foundation: http://matthew-brett.github.io/pydagogue/foundation.html
.. _deleting master on github: http://matthew-brett.github.io/pydagogue/gh_delete_master.html
.. _rebase without tears: http://matthew-brett.github.io/pydagogue/rebase_without_tears.html
.. _resolving a merge: https://schacon.github.io/git/user-manual.html#resolving-a-merge
.. _ipython git workflow: http://mail.scipy.org/pipermail/ipython-dev/2010-October/006746.html

.. other stuff
.. _python: http://www.python.org
.. _travis: https://travis-ci.org/
.. _linterflake8: https://atom.io/packages/linter-flake8

.. python packages
.. _pep8: https://pypi.python.org/pypi/pep8
.. _pyflakes: https://pypi.python.org/pypi/pyflakes
.. _coverage: https://pypi.python.org/pypi/coverage
.. _nose-timer: https://pypi.python.org/pypi/nose-timer
.. _nosetests: https://nose.readthedocs.org/en/latest/
.. _mayavi: http://mayavi.sourceforge.net/
.. _nitime: http://nipy.org/nitime/
.. _joblib: https://pypi.python.org/pypi/joblib
.. _scikit-learn: http://scikit-learn.org/stable/
.. _pysurfer: http://pysurfer.github.io/
.. _pyDICOM: https://pypi.python.org/pypi/pydicom/ 
.. _matplotlib: http://matplotlib.org/
.. _sphinx: http://sphinx-doc.org/
.. _pandas: http://pandas.pydata.org/
.. _PIL: https://pypi.python.org/pypi/PIL

.. python editors
.. _atom: https://atom.io/
.. _Spyder: http://pythonhosted.org/spyder/
.. _anaconda: http://www.continuum.io/downloads
.. _EPD: https://www.enthought.com/products/epd/
.. _sublime text: http://www.sublimetext.com/

.. _FreeSurfer: http://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall/

.. |emdash| unicode:: U+02014

.. vim: ft=rst
