.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. git stuff
.. _git: https://git-scm.com/
.. _github: https://github.com
.. _msysgit: http://code.google.com/p/msysgit/downloads/list
.. _git-osx-installer: http://code.google.com/p/git-osx-installer/downloads/list
.. _subversion: http://subversion.tigris.org/
.. _git cheat sheet: http://github.com/guides/git-cheat-sheet
.. _pro git book: https://git-scm.com/book/
.. _git svn crash course: http://git-scm.com/course/svn.html
.. _network graph visualizer: https://github.com/blog/39-say-hello-to-the-network-graph-visualizer
.. _git user manual: https://schacon.github.io/git/user-manual.html
.. _git tutorial: https://schacon.github.io/git/gittutorial.html
.. _git community book: http://book.git-scm.com/
.. _git ready: http://www.gitready.com/
.. _git casts: http://www.gitcasts.com/
.. _Fernando's git page: http://www.fperez.org/py4science/git.html
.. _git magic: http://www-cs-students.stanford.edu/~blynn/gitmagic/index.html
.. _git concepts: http://www.eecs.harvard.edu/~cduan/technical/git/
.. _git clone: http://schacon.github.com/git/git-clone.html
.. _git checkout: https://schacon.github.io/git/git-checkout.html
.. _git commit: https://schacon.github.io/git/git-commit.html
.. _git push: https://schacon.github.io/git/git-push.html
.. _git pull: https://schacon.github.io/git/git-pull.html
.. _git add: https://schacon.github.io/git/git-add.html
.. _git status: https://schacon.github.io/git/git-status.html
.. _git diff: https://schacon.github.io/git/git-diff.html
.. _git log: https://schacon.github.io/git/git-log.html
.. _git branch: https://schacon.github.io/git/git-branch.html
.. _git remote: https://schacon.github.io/git/git-remote.html
.. _git rebase: https://schacon.github.io/git/git-rebase.html
.. _git config: https://schacon.github.io/git/git-config.html
.. _why the -a flag?: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _git staging area: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _tangled working copy problem: http://tomayko.com/writings/the-thing-about-git
.. _git management: http://kerneltrap.org/Linux/Git_Management
.. _linux git workflow: http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _git foundation: http://matthew-brett.github.io/pydagogue/foundation.html
.. _deleting master on github: http://matthew-brett.github.io/pydagogue/gh_delete_master.html
.. _rebase without tears: http://matthew-brett.github.io/pydagogue/rebase_without_tears.html
.. _resolving a merge: https://schacon.github.io/git/user-manual.html#resolving-a-merge
.. _ipython git workflow: https://web.archive.org/web/*/http://mail.scipy.org/pipermail/ipython-dev/2010-October/006746.html

.. GitHub Help docs
.. _GitHub Help: https://help.github.com
.. _github-help-fork: https://help.github.com/en/articles/fork-a-repo
.. _github-help-clone: https://help.github.com/en/articles/cloning-a-repository
.. _github-help-push: https://help.github.com/en/articles/pushing-to-a-remote
.. _github-help-branch: https://help.github.com/en/articles/about-branches
.. _github-help-pr: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
.. _github-help-ssh: https://help.github.com/en/articles/connecting-to-github-with-ssh
.. _github-help-draft-pr: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
.. _github-help-convert-draft-pr: https://help.github.com/en/articles/changing-the-stage-of-a-pull-request
.. _`GitHub Learning Lab`: https://lab.github.com/

.. git clients
.. _git bash: https://gitforwindows.org/
.. _GitHub desktop: https://desktop.github.com/
.. _git-macos-download: https://git-scm.com/download/mac
.. _git-windows-download: https://git-scm.com/download/win
.. _git-install-nix: https://git-scm.com/download/linux
.. _git-install-mac: https://www.atlassian.com/git/tutorials/install-git
.. _windows subsystem for linux: https://docs.microsoft.com/en-us/windows/wsl/about

.. other stuff
.. _python: http://www.python.org
.. _travis: https://travis-ci.org/
.. _linterflake8: https://atom.io/packages/linter-flake8

.. python packages
.. _pep8: https://pypi.org/project/pep8/
.. _pyflakes: https://pypi.org/project/pyflakes
.. _coverage: https://pypi.python.org/pypi/coverage
.. _mayavi: http://https//docs.enthought.com/mayavi/mayavi/
.. _nitime: http://nipy.org/nitime/
.. _joblib: https://pypi.python.org/pypi/joblib
.. _scikit-learn: https://scikit-learn.org/stable/
.. _pysurfer: https://pysurfer.github.io/
.. _pyDICOM: https://pypi.python.org/pypi/pydicom/
.. _matplotlib: https://matplotlib.org/
.. _pandas: http://pandas.pydata.org/
.. _PIL: https://pypi.python.org/pypi/PIL

.. python editors
.. _atom: https://atom.io/
.. _Spyder: https://www.spyder-ide.org/
.. _anaconda: https://www.anaconda.com/distribution/
.. _miniconda: https://conda.io/en/latest/miniconda.html
.. _installation instructions for Anaconda: http://docs.continuum.io/anaconda/install
.. _installation instructions for Miniconda: https://conda.io/projects/conda/en/latest/user-guide/install/index.html
.. _EPD: https://www.enthought.com/products/epd/
.. _sublime text: http://www.sublimetext.com/
.. _vscode: https://code.visualstudio.com/

.. installation links
.. _FreeSurfer: https://surfer.nmr.mgh.harvard.edu/fswiki/
.. _FreeSurfer download page: https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall
.. _netpbm: http://netpbm.sourceforge.net/
.. _MacPorts: https://www.macports.org/
.. _Homebrew: https://brew.sh/
.. _XCode developer tools: http://appstore.com/mac/apple/xcode
.. _xquartz: https://www.xquartz.org/
.. _MATLAB runtime: https://www.mathworks.com/products/compiler/matlab-runtime.html
.. _MNE-C download page: http://www.nmr.mgh.harvard.edu/martinos/userInfo/data/MNE_register/index.php
.. _environment file:  https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
.. _requirements file:  https://raw.githubusercontent.com/mne-tools/mne-python/master/requirements.txt
.. _NVIDIA CUDA GPU processing: https://developer.nvidia.com/cuda-zone
.. _NVIDIA proprietary drivers: https://www.nvidia.com/Download/index.aspx

.. sphinx
.. _sphinx: http://www.sphinx-doc.org
.. _sphinx-gallery: https://sphinx-gallery.github.io
.. _rst: http://sphinx-doc.org/rest.html
.. _intersphinx: http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

.. misc
.. _Stack Overflow: https://stackoverflow.com/
.. _`GNU Make`: https://www.gnu.org/software/make/

.. vim: ft=rst
