.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. mne

.. _`MNE-Python GitHub`: https://github.com/mne-tools/mne-python
.. _`MNE-C manual`: https://mne.tools/mne-c-manual/MNE-manual-2.7.3.pdf
.. _`GitHub issues page`: https://github.com/mne-tools/mne-python/issues/
.. _`MNE Forum`: https://mne.discourse.group
.. _`MNE-BIDS-Pipeline`: https://mne.tools/mne-bids-pipeline
.. _`MNE-LSL`: https://mne.tools/mne-lsl
.. _`MNE-MATLAB`: https://github.com/mne-tools/mne-matlab
.. _`MNE-RT`: https://mne-rt-org.github.io/mne-rt/
.. _open a new issue: https://github.com/mne-tools/mne-python/issues/new/choose
.. _OpenMEEG: https://openmeeg.github.io
.. _EOSS2: https://chanzuckerberg.com/eoss/proposals/improving-usability-of-core-neuroscience-analysis-tools-with-mne-python
.. _`code of conduct`: https://github.com/mne-tools/.github/blob/main/CODE_OF_CONDUCT.md


.. TUTORIAL LINKS

.. _ft_cluster: http://www.fieldtriptoolbox.org/faq/how_not_to_interpret_results_from_a_cluster-based_permutation_test


.. git stuff

.. _git for Windows: https://gitforwindows.org/

.. other stuff

.. _mri_watershed: https://surfer.nmr.mgh.harvard.edu/fswiki/mri_watershed
.. _PhysioNet documentation page: https://physionet.org/content/eegmmidb/1.0.0/
.. _ipython blocking issue: https://github.com/ipython/ipython/issues/10384
.. _MRI scaling slides: https://www.slideshare.net/mne-python/mnepython-scale-mri

.. python packages

.. _CuPy: https://cupy.chainer.org/
.. _scikit-learn: https://scikit-learn.org/stable/
.. _matplotlib: https://matplotlib.org/
.. _towncrier: https://towncrier.readthedocs.io/
.. _sphinx-gallery: https://sphinx-gallery.github.io

.. python editors

.. _Spyder: https://www.spyder-ide.org/

.. installation links

.. _anaconda: https://www.anaconda.com/products/individual
.. _miniconda: https://conda.io/en/latest/miniconda.html
