.. mne-python
.. _`mne-python`: http://mne-tools.github.io/mne-python-intro
.. _`mne-python GitHub`: https://github.com/mne-tools/mne-python
.. _`mne-python sample dataset`: https://s3.amazonaws.com/mne-python/datasets/MNE-sample-data-processed.tar.gz
.. _`mne command line utilities`: http://www.nmr.mgh.harvard.edu/martinos/userInfo/data/MNE_register/
.. _`mne-scripts`: https://github.com/mne-tools/mne-scripts/
.. _`MNE mailing list`: http://mail.nmr.mgh.harvard.edu/mailman/listinfo/mne_analysis
.. _`GitHub issues page`: https://github.com/mne-tools/mne-python/issues/
