.. _errors: https://en.wikipedia.org/w/index.php?title=Type_I_and_type_II_errors#Table_of_error_types
.. _fwer: https://en.wikipedia.org/wiki/Family-wise_error_rate
.. _fdr: https://en.wikipedia.org/wiki/False_discovery_rate
.. _ft_cluster: http://www.fieldtriptoolbox.org/faq/how_not_to_interpret_results_from_a_cluster-based_permutation_test
.. _ft_exch: https://mailman.science.ru.nl/pipermail/fieldtrip/2008-October/001794.html
.. _ten_twenty: https://en.wikipedia.org/wiki/10%E2%80%9320_system_(EEG)
.. _ten_oh_five: https://doi.org/10.1016%2FS1388-2457%2800%2900527-7
.. _dict comprehension: https://docs.python.org/3/tutorial/datastructures.html#dictionaries
.. _spectral density: https://en.wikipedia.org/wiki/Spectral_density
