#!/usr/bin/env bash

set -eu

# Path to the directory you want to create
DIR=~/mne_data

# Check if the directory already exists
if [ -d "$DIR" ]; then
    echo "Found existing MNE data directory: $DIR"
else
    # Create the directory since it does not exist
    mkdir -p "$DIR"
    # Check if the directory creation was successful
    if [ $? -eq 0 ]; then
        echo "MNE data directory created: $DIR"
    else
        echo "Failed to create MNE data directory: $DIR"
        exit 1
    fi
fi
