# This Dockerfile is currently only used to enforce use of x86 image on ARM64 CPUs (Apple Silicon)
# See aarch64 migration on https://conda-forge.org/status/, which is currently blocking us.
FROM --platform=amd64 mcr.microsoft.com/devcontainers/base:debian-11
