# This Dockerfile is currently only used to enforce use of an x86 image on ARM64 CPUs (Apple Silicon)
# See the conda-forge aarch64 migration status at https://conda-forge.org/status/, which is currently blocking us.
FROM --platform=amd64 mcr.microsoft.com/devcontainers/base:debian-11
