name: mne
channels:
- defaults
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- traits
- pyface
- traitsui
- imageio
- tqdm
- spyder-kernels
- vtk
- pip:
  - mne
  - imageio-ffmpeg>=0.4.1
  - pyvista>=0.24
  - pyvistaqt>=0.2.0
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - python-picard
  - PyQt5>=5.10,<5.14; platform_system == "Darwin"
  - PyQt5>=5.10; platform_system != "Darwin"
