"""IO module for reading raw data."""

# Authors: Alexandre Gramfort <alexandre.gramfort@inria.fr>
#          Matti Hämäläinen <msh@nmr.mgh.harvard.edu>
#
# License: BSD-3-Clause

import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    __name__,
    submodules=[
        "array",
        "base",
        "brainvision",
        "bti",
        "cnt",
        "ctf",
        "constants",
        "edf",
        "egi",
        "fiff",
        "fil",
        "kit",
        "nicolet",
        "nirx",
        "boxy",
        "persyst",
        "eeglab",
        "pick",
        "nihon",
        "nsx",
    ],
    submod_attrs={
        "array": ["RawArray"],
        "artemis123": ["read_raw_artemis123"],
        "base": ["BaseRaw", "concatenate_raws", "match_channel_orders"],
        "besa": ["read_evoked_besa"],
        "boxy": ["read_raw_boxy"],
        "brainvision": ["read_raw_brainvision"],
        "bti": ["read_raw_bti"],
        "cnt": ["read_raw_cnt"],
        "ctf": ["read_raw_ctf"],
        "curry": ["read_raw_curry"],
        "edf": ["read_raw_edf", "read_raw_bdf", "read_raw_gdf"],
        "eeglab": ["read_raw_eeglab", "read_epochs_eeglab"],
        "egi": ["read_raw_egi", "read_evokeds_mff"],
        "eximia": ["read_raw_eximia"],
        "eyelink": ["read_raw_eyelink"],
        "fieldtrip": [
            "read_raw_fieldtrip",
            "read_epochs_fieldtrip",
            "read_evoked_fieldtrip",
        ],
        "hitachi": ["read_raw_hitachi"],
        "fiff": ["read_raw_fif", "Raw", "RawFIF"],
        "fil": ["read_raw_fil"],
        "kit": ["read_raw_kit", "read_epochs_kit"],
        "meas_info": [
            "read_fiducials",
            "write_fiducials",
            "read_info",
            "write_info",
            "_empty_info",
            "_merge_info",
            "_force_update_info",
            "Info",
            "anonymize_info",
            "_writing_info_hdf5",
        ],
        "nedf": ["read_raw_nedf"],
        "nicolet": ["read_raw_nicolet"],
        "nihon": ["read_raw_nihon"],
        "nirx": ["read_raw_nirx"],
        "nsx": ["read_raw_nsx"],
        "open": ["fiff_open", "show_fiff", "_fiff_get_fid"],
        "persyst": ["read_raw_persyst"],
        "proj": ["make_eeg_average_ref_proj", "Projection"],
        "reference": [
            "set_eeg_reference",
            "set_bipolar_reference",
            "add_reference_channels",
        ],
        "snirf": ["read_raw_snirf"],
        "tag": ["_loc_to_coil_trans", "_coil_trans_to_loc", "_loc_to_eeg_loc"],
        "_read_raw": ["read_raw"],
    },
)
