# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.4.0.dev62+g7e7d5226ae.d20230301'
__version_tuple__ = version_tuple = (1, 4, 0, 'dev62', 'g7e7d5226ae.d20230301')
