name: mne
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23
  - scipy=1.9
  - matplotlib=3.6
  - pandas=1.3.2
  - scikit-learn=1.1
  - nibabel  # whichever one works
  - tqdm
  - pooch
  - decorator
  - packaging
  - jinja2
  - lazy_loader
