name: mne
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24
  - scipy=1.10
  - matplotlib=3.6
  - pandas=1.5.2
  - scikit-learn=1.2
  - nibabel  # whichever one works
  - tqdm
  - pooch
  - decorator
  - packaging
  - jinja2
  - lazy_loader
