# Authors: The MNE-Python contributors.
# License: BSD-3-Clause
# Copyright the MNE-Python contributors.

from pathlib import Path

import tomlkit
import yaml
from packaging.requirements import Requirement


def pip_to_pixi(dependencies_list):
    """Convert pip dependency specifier strings to a pixi-style dict."""
    out = dict()
    for dep in dependencies_list:
        out[dep.name] = str(dep.specifier) if str(dep.specifier) != "" else "*"
    return out


# HACK: we place mne-* satellite packages in the pip channel so that pixi doesn't write
# mne-base into the lock file.
pypi_dependencies = sorted(["mne-qt-browser", "pymef", "mne-bids"])

repo_root = Path(__file__).resolve().parent.parent
tests_yaml_fpath = repo_root / ".github" / "workflows" / "tests.yml"
pyproject_fpath = repo_root / "pyproject.toml"
pyproject = tomlkit.loads(pyproject_fpath.read_bytes())
outfile = repo_root / "tools" / "ci" / "macos-intel" / "pixi.toml"

# handle naming differences between PyPI and conda-forge
remapping = dict(neo="python-neo")

# Specify the python version that our pixi job wants
with open(tests_yaml_fpath) as fid:
    test_yaml = yaml.safe_load(fid)

foo = test_yaml["jobs"]["pytest"]["strategy"]["matrix"]["include"]
for job in foo:
    if job["os"] == "macos-15-intel":
        python_version = job["python"]
        # Pixi complains if we don't specify a patch version
        if len(python_version.split(".")) <= 2:
            python_version += ".*"
        break

# in keys: build-system, dependency-groups, project, tool
# out keys: workspace, dependencies, pypi-dependencies (may need tasks)
out = dict()
workspace = dict(
    authors=["MNE-Python contributors"],
    channels=["conda-forge"],
    name=pyproject["project"]["name"],
    platforms=["osx-64"],
    version="0.1.0",
)

# By default, Pixi assumes the environment it is solving is compatible with macOS
# 13.0 and later, but conda-forge's libblas newaccelerate build requires macOS >=13.3.
# And below we add this build variant as a dependency.
# https://pixi.prefix.dev/v0.39.5/features/system_requirements/#__tabbed_1_3
system_requirements = dict(macos="13.3")  # Minimum version

dependencies = pyproject["project"]["dependencies"]
dependencies.extend(pyproject["dependency-groups"]["dev"])
dependencies.extend(pyproject["dependency-groups"]["test"])
dependencies.extend(pyproject["dependency-groups"]["test_extra"])
dependencies.extend(pyproject["dependency-groups"]["test_extra_ft"])
dependencies.extend(pyproject["project"]["optional-dependencies"]["hdf5"])
dependencies.extend(pyproject["project"]["optional-dependencies"]["full-no-qt"])
dependencies.extend(pyproject["project"]["optional-dependencies"]["full-pyside6"])
# exclude recursive MNE deps
dependencies = list(
    filter(lambda x: isinstance(x, str) and "mne[" not in x, dependencies)
)
# strip out platform specifiers; for now this affects only pyobj-framework-cocoa, and
# since this pixi.toml is destined for macos-intel job, we want it in there so we're
# skipping writing the logic to parse the platform spec.
for ix, dep in enumerate(dependencies):
    if (split_ix := dep.find(";")) >= 0:
        dependencies[ix] = dep[:split_ix].strip()
# handle mismatch between names on PyPI and conda-forge
dependencies = [remapping.get(dep, dep) for dep in dependencies]
dependencies.sort()

# exclude pypi-only deps
dependencies = [Requirement(dep) for dep in dependencies]
pypi_dependencies = [Requirement(dep) for dep in pypi_dependencies]

dependencies = [
    dep
    for dep in dependencies
    if dep.name not in {pdep.name for pdep in pypi_dependencies}
]
dependencies_out = pip_to_pixi(dependencies)
# Our tests run faster with Apple's Accelerate BLAS numerical backend.
dependencies_out["libblas"] = {"version": "*", "build": "*_newaccelerate"}

out = {
    "workspace": workspace,
    "system-requirements": system_requirements,
    "dependencies": dependencies_out,
    "pypi-dependencies": pip_to_pixi(pypi_dependencies),
}
out["dependencies"].update(python=python_version)

doc = tomlkit.document()
doc.add(
    tomlkit.comment(
        "THIS FILE IS AUTO-GENERATED BY tools/write_pixi_toml.py AND WILL BE OVERWRITTEN"  # noqa E501
    )
)
doc.update(out)
# write the file
outfile.parent.mkdir(parents=True, exist_ok=True)
with open(outfile, "w") as fid:
    tomlkit.dump(doc, fid, sort_keys=False)
