name: autofix.ci

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  autofix-changelog-headers:
    name: Autoupdate changelog entry and headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6.3.0
      - run: pip install --upgrade towncrier pygithub gitpython numpy
      - run: python ./.github/actions/rename_towncrier/rename_towncrier.py
      - run: python ./tools/dev/ensure_headers.py
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
  autofix-citation-codemeta:
    ### TODO: Remove before merging ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    name: Autoupdate CITATION.cff and codemeta.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Generate citation
        uses: tsbinns/mne-tools/actions/generate-citation@add_tools
        with:
          project-root: ${{ github.workspace }}
          release-version: "1.13.0"
      - name: Generate codemeta
        uses: tsbinns/mne-tools/actions/generate-codemeta@add_tools
        with:
          project-root: ${{ github.workspace }}
          release-version: "1.13.0"
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
  autofix-dependencies:
    name: Autoupdate 'old' CI lockfile, README dependencies, and environment file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          version: ">=0.9"
          activate-environment: true
          python-version: "3.12"
      - name: Update 'old' CI lockfile
        # uv pip compile requires setting the python version for the environment explicitly in the command :(
        run: |
          uv pip compile pyproject.toml \
          --python "3.10" --python-platform "x86_64-unknown-linux-gnu" \
          --group test --group lockfile_extras \
          --resolution lowest-direct \
          --format pylock.toml --output-file tools/pylock.ci-old.toml \
          --no-cache
      - name: Validate 'old' CI lockfile
        uses: tsbinns/mne-tools/actions/check-lockfile@add_tools
        with:
          project-root: ${{ github.workspace }}
          lockfile-path: tools/pylock.ci-old.toml
          groups: lockfile_extras
      - name: Sync dependencies to README
        uses: tsbinns/mne-tools/actions/sync-dependencies-to-readme@add_tools
        with:
          project-root: ${{ github.workspace }}
          ignore-upper-pins: numpy
      - name: Sync dependencies to environment file
        uses: tsbinns/mne-tools/actions/sync-dependencies-to-environment-file@add_tools
        with:
          project-root: ${{ github.workspace }}
          extras: full,full-no-qt,hdf5
          additional-dependencies: pip,mamba,conda,nomkl,noqt5
          pip-dependencies: pymef
          requirements-overrides: PySide6==6.10.2,vtk==9.6.0
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
