# https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks
name: Cancel
on:
  workflow_run:
    # https://api.github.com/repos/mne-tools/mne-python/actions/workflows
    workflows: ["compat / minimal", "compat / old", "linux / conda", "linux / pip-pre", "macos / conda"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
