name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  osx:
    name: OSX
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    env:
      PYTHON_VERSION: '3.7'
      MNE_LOGGING_LEVEL: 'warning'
      CONDA_VERSION: '>=4.3.27'
      OPENBLAS_NUM_THREADS: '1'
      PYTHONUNBUFFERED: '1'
      CONDA_ENV: 'environment.yml'
      TRAVIS_OS_NAME: 'osx'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: 'mne'
          python-version: ${{ env.PYTHON_VERSION }}
          environment-file: ${{ env.CONDA_ENV }}
        name: 'Setup conda'
      - shell: bash -l {0}
        run: |
          pip uninstall -yq mne
          pip install --upgrade -r requirements_testing.txt
          pip install nitime
          source tools/get_minimal_commands.sh
          mne_surf2bem --version
        name: 'Install dependencies'
      - shell: bash -l {0}
        run: |
          python setup.py build
          python setup.py install
          mne sys_info
          python -c "import numpy; numpy.show_config()"
        name: 'Install MNE'
      - shell: bash -l {0}
        run: |
          python -c 'import mne; mne.datasets.testing.data_path(verbose=True)';
        name: 'Download testing data'
      - shell: bash -l {0}
        run: |
          echo 'pytest -m "${CONDITION}" --tb=short --cov=mne -vv ${USE_DIRS}'
          pytest -m "${CONDITION}" --tb=short --cov=mne -vv ${USE_DIRS}
        env:
          CONDITION: 'not slowtest'
          USE_DIRS: 'mne/'
        name: 'Testing'
