name: Generate citation

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  generate-citation:
    permissions:
      contents: write
    name: Generate citation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - name: Run MNE-Tools action
        uses: tsbinns/mne-tools/actions/generate-citation@add_tools
        with:
          project-root: ${{ github.workspace }}
          release-version: "1.13.0"
