name: 'maint'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  style:
    if: "github.repository == 'mne-tools/mne-python' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install flake8
        name: 'Install dependencies'
      - uses: rbialon/flake8-annotations@v1
        name: 'Setup flake8 annotations'
      - run: make flake
        name: 'Run flake8'
