name: SPEC0

on:  # yamllint disable-line rule:truthy
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # At 00:00 every Monday
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable ssh debugging'
        required: false
        default: false
        type: boolean

jobs:
  update_versions:
    permissions:
      contents: write
      pull-requests: write
    name: Update dependency versions
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: true
      - name: Triage SSH
        run: |
          if [[ "${{ inputs.ssh }}" == "true" ]] || [[ "$COMMIT_MESSAGE" == *"[actions ssh]"* ]]; then
            echo "ENABLE_SSH=true" | tee -a $GITHUB_ENV
          else
            echo "ENABLE_SSH=false" | tee -a $GITHUB_ENV
          fi
      - name: Setup Remote SSH Connection
        if: env.ENABLE_SSH == 'true'
        uses: Warpbuilds/action-debugger@v1.3
        timeout-minutes: 10
        with:
          detached: true
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
      - name: Install dependencies
        run: pip install --upgrade packaging requests tomlkit
      - name: Update tracked dependencies
        run: python ./tools/dev/spec_zero_update_versions.py
      - name: check if files changed
        run: |
          git diff && git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
        id: status
      - name: Show diff
        run: git diff
        if: steps.status.outputs.dirty == 'true'
