name: SPEC0

on:  # yamllint disable-line rule:truthy
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # At 00:00 every Monday
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable ssh debugging'
        required: false
        default: false
        type: boolean

jobs:
  update_versions:
    permissions:
      contents: write
      pull-requests: write
    name: Update dependency versions
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: true
      - name: Triage SSH
        run: |
          if [[ "${{ inputs.ssh }}" == "true" ]] || [[ "$COMMIT_MESSAGE" == *"[actions ssh]"* ]]; then
            echo "ENABLE_SSH=true" | tee -a $GITHUB_ENV
          else
            echo "ENABLE_SSH=false" | tee -a $GITHUB_ENV
          fi
      - name: Setup Remote SSH Connection
        if: env.ENABLE_SSH == 'true'
        uses: Warpbuilds/action-debugger@v1.3
        timeout-minutes: 10
        with:
          detached: true
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          version: ">=0.9,<=0.11.16"
          activate-environment: true
          python-version: "3.12"
      - name: Install dependencies
        run: uv pip install -e . packaging requests tomlkit
      - name: Update tracked dependencies
        run: python ./tools/dev/spec_zero_update_versions.py
      - name: Sync updated dependencies to README
        uses: tsbinns/mne-tools/actions/sync-dependencies-to-readme@add_tools
        with:
          project-root: ${{ github.workspace }}
          ignore-upper-pins: numpy
      - name: Sync updated dependencies to environment file
        uses: tsbinns/mne-tools/actions/sync-dependencies-to-environment-file@add_tools
        with:
          project-root: ${{ github.workspace }}
          extras: full,full-no-qt,hdf5
          additional-dependencies: pip,mamba,conda,nomkl,noqt5
          pip-dependencies: pymef
          requirements-overrides: PySide6==6.10.2,vtk==9.6.0
      - name: Create lockfile for old CI
        # uv pip compile requires setting the python version explicitly in the command :(
        run: uv pip compile pyproject.toml --python "3.10" --python-platform "x86_64-unknown-linux-gnu" --group test --group lockfile_extras --resolution lowest-direct --format pylock.toml --output-file tools/pylock.ci-old.toml
      - name: Validate lockfile for old CI
        uses: tsbinns/mne-tools/actions/check-lockfile@add_tools
        with:
          project-root: ${{ github.workspace }}
          lockfile-path: tools/pylock.ci-old.toml
          groups: lockfile_extras
      - name: check if files changed
        run: |
          git diff && git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
        id: status
      - name: Run pre-commit hooks to update other files
        run: |
          uv pip install pre-commit
          pre-commit run --all || true
        if: steps.status.outputs.dirty == 'true'
      - name: Show diff
        run: git diff -- ':!pylock.ci-old.toml'
        if: steps.status.outputs.dirty == 'true'
