name: Sync dependencies to README

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  sync_deps:
    permissions:
      contents: write
    name: Sync dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - name: Run MNE-Tools action
        uses: tsbinns/mne-tools/actions/sync-dependencies-to-readme@add_tools
        with:
          project-root: ${{ github.workspace }}
          ignore-upper-pins: numpy
