name: Sync dependencies to environment file

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable ssh debugging'
        required: false
        default: false
        type: boolean

jobs:
  sync_deps:
    permissions:
      contents: write
    name: Sync dependencies
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: true
      - name: Triage SSH
        run: |
          if [[ "${{ inputs.ssh }}" == "true" ]] || [[ "$COMMIT_MESSAGE" == *"[actions ssh]"* ]]; then
            echo "ENABLE_SSH=true" | tee -a $GITHUB_ENV
          else
            echo "ENABLE_SSH=false" | tee -a $GITHUB_ENV
          fi
      - name: Setup Remote SSH Connection
        if: env.ENABLE_SSH == 'true'
        uses: Warpbuilds/action-debugger@v1.3
        timeout-minutes: 10
        with:
          detached: true
      - name: Run MNE-Tools action
        uses: tsbinns/mne-tools/actions/sync_dependencies_to_environment_file@add_tools
        with:
          project-root: ${{ github.workspace }}
          extras: full,full-no-qt,hdf5
          additional-dependencies: pip,mamba,conda,nomkl,noqt5
          pip-dependencies: pymef
          requirements-overrides: PySide6==6.10.2,vtk==9.6.0
