.. _Aaron Earle-Richardson: https://github.com/Aaronearlerichardson
.. _Abram Hindle: https://softwareprocess.es
.. _Achilleas Koutsou: https://github.com/achilleas-k
.. _Adam Li: https://github.com/adam2392
.. _Adeline Fecker: https://github.com/adelinefecker
.. _Adina Wagner: https://github.com/adswa
.. _Adonay Nunes: https://github.com/AdoNunes
.. _Akhilesh S. Yadav: https://github.com/YadavAkhileshh
.. _Akshay: https://github.com/Akshay0724
.. _Alan Leggitt: https://github.com/leggitta
.. _Alejandro Santos Mayo: https://github.com/ASantosMayo
.. _Alejandro Weinstein: http://ocam.cl
.. _Alessandro Tonin: https://www.linkedin.com/in/alessandro-tonin-7892b046
.. _Alex Ciok: https://github.com/alexCiok
.. _Alex Gramfort: https://alexandre.gramfort.net
.. _Alex Lepauvre: https://github.com/AlexLepauvre
.. _Alex Rockhill: https://github.com/alexrockhill/
.. _Alexander Kiefer: https://home.alexk101.dev
.. _Alexander Rudiuk: https://github.com/ARudiuk
.. _Alexandra Corneyllie: https://github.com/Lx37
.. _Alexandre Barachant: https://alexandre.barachant.org
.. _Aman Srivastava: https://github.com/aman-coder03
.. _Ana Radanovic: https://github.com/anaradanovic
.. _Andrea Brovelli: https://brovelli.github.io/
.. _Andreas Højlund: https://github.com/ahoejlund
.. _Andres Rodriguez: https://github.com/infinitejest/
.. _Andrew Dykstra: https://scholar.google.com/citations?hl=en&user=uCxafoMAAAAJ
.. _Andrew Gilbert: https://github.com/adgilbert
.. _Andrew Quinn: https://github.com/ajquinn
.. _Aniket Pradhan: https://github.com/Aniket-Pradhan
.. _Aniket Singh Yadav: https://github.com/Aniketsy
.. _Anna Padee: https://github.com/apadee/
.. _Annalisa Pascarella: https://github.com/annapasca
.. _Anne-Sophie Dubarry: https://github.com/annesodub
.. _Antoine Collas: https://www.antoinecollas.fr
.. _Antoine Gauthier: https://github.com/Okamille
.. _Anton Karpov: https://github.com/karpovantonme
.. _Anton Nikolas Waniek: https://github.com/antonwnk
.. _Antti Rantala: https://github.com/Odingod
.. _Apoorva Karekal: https://github.com/apoorva6262
.. _Apoorva Verma: https://github.com/apoorva-01
.. _Archit Singhal: https://github.com/architsinghal-mriirs
.. _Ariel Rokem: https://github.com/arokem
.. _Arne Pelzer: https://github.com/aplzr
.. _Ashley Drew: https://github.com/ashdrew
.. _Asish Panda: https://github.com/kaichogami
.. _Athish M: https://github.com/athishdresu
.. _Austin Hurst: https://github.com/a-hurst
.. _Ayushi Satodiya: https://github.com/ayuclan
.. _Baris Talar: https://github.com/baris-talar
.. _Basile Pinsard: https://github.com/bpinsard
.. _Beige Jerry Jin: https://github.com/BeiGeJin
.. _Beliz Sertcan Gökmen: https://github.com/BelizSertcan
.. _Ben Beasley: https://github.com/musicinmybrain
.. _Ben Tang: https://github.com/bentang18
.. _Benedikt Ehinger: https://www.benediktehinger.de
.. _Bhargav Kowshik: https://github.com/bkowshik
.. _Brad Buran: https://github.com/bburan
.. _Bradley Voytek: https://github.com/voytek
.. _Britta Westner: https://britta-wstnr.github.io
.. _Bruno Aristimunha: https://bruaristimunha.github.io
.. _Bruno Nicenboim: https://bnicenboim.github.io
.. _btkcodedev: https://github.com/btkcodedev
.. _buildqa: https://github.com/buildqa
.. _Burkhard Maess: https://github.com/bmaess
.. _Camilo Lamus: https://github.com/clamus
.. _Carina Forster: https://github.com/CarinaFo
.. _Carlos de la Torre-Ortiz: https://github.com/c-torre
.. _Catalina María Galván: https://github.com/catalinamagalvan
.. _Cathy Nangini: https://github.com/KatiRG
.. _Cedric Conday: https://github.com/CedricConday
.. _Chetan Gohil: https://github.com/cgohil8
.. _Chris Bailey: https://github.com/cjayb
.. _Chris Holdgraf: https://chrisholdgraf.com
.. _Chris Mullins: https://crmullins.com
.. _Christian Brodbeck: https://github.com/christianbrodbeck
.. _Christian Clauss: https://github.com/cclauss
.. _Christian Mista: https://github.com/cmista
.. _Christian O'Reilly: https://github.com/christian-oreilly
.. _Christina Zhao: https://github.com/ChristinaZhao
.. _Christodoulos Kechris: https://github.com/christodouloskech
.. _Christoph Huber-Huber: https://github.com/chsquare
.. _Christopher Dinh: https://github.com/chdinh
.. _Christopher Mullins: https://github.com/chrismullins
.. _Chun-Hui Li: https://github.com/iamsc
.. _Claire Braboszcz: https://github.com/claire-braboszcz
.. _Clemens Brunner: https://github.com/cbrnr
.. _Clément Moutard: https://github.com/cmoutard
.. _Cora Kim: https://github.com/kimcoco
.. _Cristóbal Moënne-Loccoz: https://github.com/cmmoenne
.. _Dan Wakeman: https://github.com/dgwakeman
.. _Daniel Carlström Schad: https://github.com/DanielCSchad
.. _Daniel Hasegan: https://daniel.hasegan.com
.. _Daniel McCloy: https://dan.mccloy.info
.. _Daniel Strohmeier: https://github.com/joewalter
.. _Daniel Tse: https://github.com/Xiezhibin
.. _Daria Agafonova: https://github.com/viranovskaya
.. _Darin Erat Sleiter: https://github.com/dsleiter
.. _Darlene Heliokinde: https://github.com/kostasde
.. _David Haslacher: https://github.com/davidhaslacher
.. _David Julien: https://github.com/Swy7ch
.. _David Sabbagh: https://github.com/DavidSabbagh
.. _Deep Kaur: https://github.com/Dpereaptkhamur-13
.. _Denis Engemann: https://denis-engemann.de
.. _Desislava Petkova: https://github.com/dipetkov
.. _Dev Parikh: https://github.com/devparikh0506
.. _Dimitri Papadopoulos Orfanos: https://github.com/DimitriPapadopoulos
.. _Dinara Issagaliyeva: https://github.com/dissagaliyeva
.. _Diptyajit Das: https://github.com/dasdiptyajit
.. _Dirk Gütlin: https://github.com/DiGyt
.. _Dmitrii Altukhov: https://github.com/dmalt
.. _Dominik Krzemiński: https://github.com/dokato
.. _Dominik Welke: https://github.com/dominikwelke/
.. _Dominik Wetzel: https://github.com/schmetzler
.. _Dominique Makowski: https://dominiquemakowski.github.io/
.. _Eberhard Eich: https://github.com/ebeich
.. _Eduard Ort: https://github.com/eort
.. _Elizabeth DuPre: https://github.com/emdupre
.. _Ellen Lau: https://github.com/ellenlau
.. _Emanuele Olivetti: https://github.com/emanuele
.. _Emily Stephen: https://github.com/emilyps14
.. _Emma Bailey: https://github.com/emma-bailey
.. _Emma Zhang: https://portfolio-production-ed03.up.railway.app/
.. _Emmanuel Ferdman: https://github.com/emmanuel-ferdman
.. _Emrecan Çelik: https://github.com/emrecncelik
.. _Enrico Varano: https://github.com/enricovara/
.. _Enzo Altamiranda: https://www.linkedin.com/in/enzoalt
.. _Eric Brayet: https://github.com/mbt-eric-b
.. _Eric Larson: https://larsoner.com
.. _Erica Peterson: https://github.com/nordme
.. _Erik Hornberger: https://github.com/moppymopperson
.. _Erkka Heinila: https://github.com/Teekuningas
.. _Etienne de Montalivet: https://github.com/etiennedemontalivet
.. _Evan Hathaway: https://github.com/ephathaway
.. _Evgenii Kalenkovich: https://github.com/kalenkovich
.. _Evgeny Goldstein: https://github.com/evgenygoldstein
.. _Ezequiel Mikulan: https://github.com/ezemikulan
.. _Fahimeh Mamashli: https://github.com/fmamashli
.. _Famous Raj Bhat: https://github.com/Famous077
.. _Farzah11: https://github.com/Farzah11
.. _Farzin Negahbani: https://github.com/Farzin-Negahbani
.. _Federico Raimondo: https://github.com/fraimondo
.. _Federico Zamberlan: https://github.com/fzamberlan
.. _Felix Klotzsche: https://github.com/eioe
.. _Félix Raimundo: https://github.com/gamazeps
.. _Florian Hofer: https://github.com/hofaflo
.. _Florin Pop: https://github.com/florin-pop
.. _Frankie Robertson: https://github.com/frankier
.. _Frederik D. Weber: https://github.com/Frederik-D-Weber
.. _Fu-Te Wong: https://github.com/zuxfoucault
.. _Gansheng Tan: https://github.com/GanshengT
.. _Gennadiy Belonosov: https://github.com/Genuster
.. _Geoff Brookshire: https://github.com/gbrookshire
.. _George O'Neill: https://georgeoneill.github.io
.. _Giorgio Marinato: https://github.com/neurogima
.. _Giulio Gabrieli: https://github.com/Gabrock94
.. _Gnaneswar Lopinti: https://github.com/flying-spagetti
.. _Gonzalo Reina: https://orcid.org/0000-0003-4219-2306
.. _Guillaume Dumas: https://mila.quebec/en/person/guillaume-dumas
.. _Guillaume Favelier: https://github.com/GuillaumeFavelier
.. _Hafeza Anevar: https://github.com/Anevar
.. _Hakimeh Aslsardroud: https://www.researchgate.net/profile/Hakimeh-Pourakbari
.. _Hakimeh Pourakbari: https://github.com/Hpakbari
.. _Hamid Maymandi: https://github.com/HamidMandi
.. _Hamza Abdelhedi: https://github.com/BabaSanfour
.. _Hansuja Budhiraja: https://github.com/HansujaB
.. _Hari Bharadwaj: https://github.com/haribharadwaj
.. _Harrison Ritz: https://github.com/harrisonritz
.. _Hasrat Ali Arzoo: https://github.com/hasrat17
.. _Henrich Kolkhorst: https://github.com/hekolk
.. _Himanshu Mahor: https://github.com/1himan
.. _Hongjiang Ye: https://github.com/ye-hongjiang
.. _Hubert Banville: https://github.com/hubertjb
.. _Hüseyin Orkun Elmas: https://github.com/HuseyinOrkun
.. _Hyonyoung Shin: https://github.com/mcvain
.. _Ilian Azz: https://github.com/ilianAZZ
.. _Ilias Machairas: https://github.com/JungleHippo
.. _Ivan Skelin: https://github.com/ivan-skelin
.. _Ivan Zubarev: https://github.com/zubara
.. _Ivana Kojcic: https://github.com/ikojcic
.. _Ivo de Jong: https://github.com/ivopascal
.. _Jaakko Leppakangas: https://github.com/jaeilepp
.. _Jack Zhang: https://github.com/jackz314
.. _Jacob Phelan: https://github.com/JacPhe
.. _Jacob Woessner: https://github.com/withmywoessner
.. _Jair Montoya Martinez: https://github.com/jmontoyam
.. _Jakub Kaczmarzyk: https://github.com/kaczmarj
.. _Jan Ebert: https://www.jan-ebert.com/
.. _Jan Mathijs Schoffelen: https://github.com/schoffelen
.. _Jan Sedivy: https://github.com/honzaseda
.. _Jan Sosulski: https://jan-sosulski.de
.. _Jan Zerfowski: https://github.com/jzerfowski
.. _Jasper J.F. van den Bosch: https://github.com/JasperVanDenBosch
.. _Jasper van den Bosch: https://github.com/ilogue
.. _Jean-Baptiste Schiratti: https://github.com/jbschiratti
.. _Jean-Rémi King: https://github.com/kingjr
.. _Jeff Stout: https://megcore.nih.gov/index.php/Staff
.. _Jen Evans: https://github.com/jwe080
.. _Jennifer Behnke: https://github.com/JKBehnke
.. _Jeroen Van Der Donckt: https://github.com/jvdd
.. _Jesper Duemose Nielsen: https://github.com/jdue
.. _Jevri Hanna: https://github.com/jshanna100
.. _Joan Massich: https://github.com/massich
.. _Johan van der Meer: https://github.com/jnvandermeer
.. _Johann Benerradi: https://github.com/HanBnrd
.. _Johannes Herforth: https://herforth.net
.. _Johannes Kasper: https://github.com/jeythekey
.. _Johannes Niediek: https://github.com/jniediek
.. _John Griffiths: https://www.grifflab.com
.. _John Samuelsson: https://github.com/johnsam7
.. _John Veillette: https://psychology.uchicago.edu/directory/john-veillette
.. _Jon Houck: https://www.mrn.org/people/jon-m.-houck/principal-investigators
.. _Jona Sassenhagen: https://github.com/jona-sassenhagen
.. _Jonas Mago: https://github.com/jonasmago
.. _Jonathan Kuziek:  https://github.com/kuziekj
.. _Jordan Drew: https://github.com/jadrew43
.. _Joris Van den Bossche: https://github.com/jorisvandenbossche
.. _José C. García Alanis: https://github.com/JoseAlanis
.. _Josh Koen: https://github.com/jdkoen
.. _Joshua Bear: https://github.com/joshbear
.. _Joshua Calder-Travis: https://github.com/jCalderTravis
.. _Joshua Teves: https://github.com/jbteves
.. _Judy D Zhu: https://github.com/JD-Zhu
.. _Juergen Dammers: https://github.com/jdammers
.. _Jukka Nenonen: https://www.linkedin.com/pub/jukka-nenonen/28/b5a/684
.. _Julia Guiomar Niso Galán: https://github.com/guiomar
.. _Julien Dubois: https://github.com/jcrdubois
.. _Julius Welzel: https://github.com/JuliusWelzel
.. _Jussi Nurminen: https://github.com/jjnurminen
.. _Justus Schwabedal: https://github.com/jusjusjus
.. _Kaisu Lankinen: http://bishoplab.berkeley.edu/Kaisu.html
.. _Kalle Makela: https://github.com/Kallemakela
.. _Kalle Mäkelä: https://github.com/kalomak
.. _Kambiz Tabavi: https://github.com/ktavabi
.. _Katarina Slama: https://github.com/katarinaslama
.. _Katia Al-Amir: https://github.com/katia-sentry
.. _Katrin Leinweber: https://github.com/katrinleinweber
.. _Kay Robbins: https://github.com/VisLab
.. _Keith Doelling: https://github.com/kdoelling1919
.. _Kevin Schiesser: https://github.com/kevinjos
.. _Konstantinos Tsilimparis: https://contsili.github.io/
.. _Kostiantyn Maksymenko: https://github.com/makkostya
.. _Kristijan Armeni: https://github.com/kristijanarmeni
.. _Kyle Mathewson: https://github.com/kylemath
.. _Laetitia Grabot: https://github.com/LaetitiaG
.. _Larry Eisenman:  https://github.com/lneisenman
.. _Lau Møller Andersen: https://github.com/ualsbombe
.. _Laura Gwilliams: https://lauragwilliams.github.io
.. _Laurent Le Mentec: https://github.com/LaurentLM
.. _Leonardo Barbosa: https://github.com/noreun
.. _Leonardo Rochael Almeida: https://github.com/leorochael
.. _Liberty Hamilton: https://github.com/libertyh
.. _Lifeng Qiu Lin: https://github.com/Gnefil
.. _Lorenz Esch: https://github.com/LorenzE
.. _Lorenzo Alfine: https://github.com/lorrandal
.. _Lorenzo Desantis: https://github.com/lorenzo-desantis/
.. _Louis Thibault: https://github.com/lthibault
.. _Luca Kaemmer: https://github.com/Lucakaemmer
.. _Lukas Breuer: https://www.researchgate.net/profile/Lukas-Breuer-2
.. _Lukas Gemein: https://github.com/gemeinl
.. _Lukas Hecker: https://github.com/LukeTheHecker
.. _Lukáš Hejtmánek: https://github.com/hejtmy
.. _Luke Bloy: https://www.research.chop.edu/imaging/team
.. _luz paz: https://github.com/luzpaz
.. _Mads Jensen: https://github.com/MadsJensen
.. _Maggie Clarke: https://github.com/mdclarke
.. _Mainak Jas: https://jasmainak.github.io
.. _Maksym Balatsko: https://github.com/mbalatsko
.. _manoj kumar: https://github.com/MechCoder
.. _Manorama Kadwani: https://github.com/synapse-stream
.. _Manu Sutela: https://github.com/MJAS1
.. _Marcin Koculak: https://github.com/mkoculak
.. _Marian Dovgialo: https://github.com/mdovgialo
.. _Marijn van Vliet: https://github.com/wmvanvliet
.. _Mark Alexander Henney: https://github.com/henneysq
.. _Mark Wronkiewicz: https://github.com/wronk
.. _Marmaduke Woodman: https://github.com/maedoc
.. _Martin BaBer: https://github.com/MartinBaBer
.. _Martin Billinger: https://github.com/mbillingr
.. _Martin Luessi: https://github.com/mluessi
.. _Martin Oberg: https://github.com/obergmartin
.. _Martin Perez-Guevara: https://github.com/MartinPerez
.. _Martin Schulz: https://github.com/marsipu
.. _Martin van Harmelen: https://github.com/MPvHarmelen
.. _Mathias Sablé-Meyer: https://s-m.ac/
.. _Mathieu Scheltienne: https://github.com/mscheltienne
.. _Mathurin Massias: https://mathurinm.github.io/
.. _Mats van Es: https://github.com/matsvanes
.. _Matt Boggess: https://github.com/mattboggess
.. _Matt Courtemanche: https://github.com/mjcourte
.. _Matt Sanderson: https://github.com/monkeyman192
.. _Matteo Anelli: https://github.com/matteoanelli
.. _Matteo Visconti di Oleggio Castello: https://github.com/mvdoc
.. _Matthew A. Tucker: https://github.com/matthew-tucker
.. _Matthias Dold: https://matthiasdold.de
.. _Matthias Eberlein: https://github.com/MatthiasEb
.. _Matti Hämäläinen: https://research.aalto.fi/en/persons/matti-h%C3%A4m%C3%A4l%C3%A4inen/
.. _Matti Toivonen: https://github.com/mattitoi
.. _Maureen Shader: https://github.com/mshader
.. _Mauricio Cespedes Tenorio: https://github.com/mcespedes99
.. _Melih Yayli: https://github.com/yaylim
.. _Michael Krause: https://github.com/octomike
.. _Michael Straube: https://github.com/mistraube
.. _Michal Žák: https://github.com/michalrzak
.. _Michiru Kaneda: https://github.com/rcmdnk
.. _Mikołaj Magnuski: https://github.com/mmagnuski
.. _Milan Rybář: https://milanrybar.cz
.. _Mingjian He: https://github.com/mh105
.. _Mohamed Sherif: https://github.com/mohdsherif
.. _Mohammad Daneshzand: https://github.com/mdaneshzand
.. _Mojackhak: https://github.com/Mojackhak
.. _Moritz Gerster: https://github.com/moritz-gerster
.. _Motofumi Fushimi: https://github.com/motofumi-fushimi
.. _Nabil Alibou: https://github.com/nabilalibou
.. _Natalie Klein: https://github.com/natalieklein
.. _Nataliia Kozhemiako: https://github.com/NataKozh
.. _Nathalie Gayraud: https://github.com/ngayraud
.. _Natneal B: https://github.com/natinew77-creator
.. _Naveen Srinivasan: https://github.com/naveensrinivasan
.. _Nick Foti: https://nfoti.github.io
.. _Nick Ward: https://profiles.ucl.ac.uk/10827-nick-ward
.. _Nicolas Barascud: https://github.com/nbara
.. _Nicolas Fourcaud-Trocmé: https://www.crnl.fr/fr/user/316
.. _Nicolas Gensollen: https://github.com/NicolasGensollen
.. _Nicolas Legrand: https://github.com/LegrandNico
.. _Nicole Proulx: https://github.com/nicproulx
.. _Niels Focke: https://neurologie.umg.eu/forschung/arbeitsgruppen/epilepsie-und-bildgebungsforschung
.. _Niklas Wilming: https://github.com/nwilming
.. _Nikolai Chapochnikov: https://github.com/chapochn
.. _Nikolai Kapralov: https://github.com/ctrltz
.. _Nikolas Chalas: https://github.com/Nichalas
.. _Noah Markowitz: https://github.com/nmarkowitz
.. _Okba Bekhelifi: https://github.com/okbalefthanded
.. _Olaf Hauk: https://neuroscience.cam.ac.uk/member/olafhauk
.. _Ole Jensen: https://www.psy.ox.ac.uk/people/ole-jensen
.. _Oleh Kozynets: https://github.com/OlehKSS
.. _Omer Shubi: https://github.com/OmerShubi
.. _Pablo Arias Sarah: https://github.com/Pablo-Arias
.. _Pablo Mainar: https://github.com/pablomainar
.. _Padma Sundaram: https://www.nmr.mgh.harvard.edu/user/8071
.. _Paul Anders: https://github.com/Mettphysik
.. _Paul Pasler: https://github.com/ppasler
.. _Paul Roujansky: https://github.com/paulroujansky
.. _Pavel Navratil: https://github.com/navrpa13
.. _Pavel Popov: https://github.com/paavalipopov
.. _Payam Sadeghi-Shabestari: https://github.com/payamsash
.. _Pedro Silva: https://github.com/pbnsilva
.. _Peter Molfese: https://github.com/pmolfese
.. _Phillip Alday: https://palday.bitbucket.io
.. _Pierre Ablin: https://pierreablin.com
.. _Pierre Guetschel: https://github.com/PierreGtch
.. _Pierre-Antoine Bannier: https://github.com/PABannier
.. _Ping-Keng Jao: https://github.com/nafraw
.. _Piotr Durka: https://github.com/pjdurka
.. _Pragnya Khandelwal: https://github.com/PragnyaKhandelwal
.. _Praveen Sripad: https://github.com/pravsripad
.. _Proloy Das: https://github.com/proloyd
.. _Qian Chu: https://github.com/qian-chu
.. _Qianliang Li: https://www.dtu.dk/english/service/phonebook/person?id=126774
.. _Quentin Barthélemy: https://github.com/qbarthelemy
.. _Quentin Bertrand: https://github.com/QB3
.. _Qunxi Dong: https://github.com/dongqunxi
.. _Rahul Nadkarni: https://github.com/rahuln
.. _Ram Pari: https://github.com/ramkpari
.. _Ramiro Gatti: https://github.com/ragatti
.. _ramonapariciog: https://github.com/ramonapariciog
.. _Raphaël Bordas: https://github.com/raphbrd
.. _Rasmus Aagaard: https://github.com/rasgaard
.. _Rasmus Zetter: https://github.com/rzetter
.. _Reza Nasri: https://github.com/rznas
.. _Reza Shoorangiz: https://github.com/rezashr
.. _Richard Höchenberger: https://github.com/hoechenberger
.. _Richard M. Köhler: https://github.com/richardkoehler
.. _Richard Scholz: https://github.com/scholzri
.. _Riessarius Stargardsky: https://github.com/Riessarius
.. _Roan LaPlante: https://github.com/aestrivex
.. _Robert Luke: https://github.com/rob-luke
.. _Robert Oostenveld: https://github.com/robertoostenveld
.. _Robert Seymour: https://neurofractal.github.io
.. _Robin Tibor Schirrmeister: https://github.com/robintibor
.. _Rodrigo Hübner: https://github.com/rodrigohubner
.. _Roeland Hancock: https://github.com/rhancockn
.. _Romain Derollepot: https://github.com/rderollepot
.. _Romain Trachel: https://fr.linkedin.com/in/trachelr
.. _Roman Goj: https://romanmne.blogspot.co.uk
.. _Rongfei Jin: https://github.com/greasycat
.. _Ross Maddox: https://medicine.umich.edu/dept/khri/ross-maddox-phd
.. _Rotem Falach: https://github.com/Falach
.. _Roy Eric Wieske: https://github.com/Randomidous
.. _Ryan Law: https://github.com/rmc-law
.. _Sagun Pai: https://github.com/Famguy
.. _Saket Choudhary: https://github.com/saketkc
.. _Sam Perry: https://github.com/Pezz89
.. _Samarth D N: https://github.com/TheGreatApollyon
.. _sametseckın: https://github.com/sametSeckiiin
.. _Sammi Chekroud: https://github.com/schekroud
.. _Samu Taulu: https://phys.washington.edu/people/samu-taulu
.. _Samuel Deslauriers-Gauthier: https://github.com/sdeslauriers
.. _Samuel Louviot: https://github.com/Sam54000
.. _Samuel Powell: https://github.com/samuelpowell
.. _Santeri Ruuskanen: https://github.com/ruuskas
.. _Santi Martínez: https://github.com/szz-dvl
.. _Sara Sommariva: https://github.com/sarasommariva
.. _Sawradip Saha: https://sawradip.github.io/
.. _Scott Huberty:  https://orcid.org/0000-0003-2637-031X
.. _Sebastiaan Mathot: https://www.cogsci.nl/smathot
.. _Sebastián Castaño-Candamil: https://github.com/jscastanoc
.. _Sebastian Jentschke: https://github.com/sjentsch
.. _Sebastian Major: https://github.com/major-s
.. _Sébastien Marti: https://www.researchgate.net/profile/Sebastien-Marti
.. _Sebastien Treguer: https://github.com/FinLouarn
.. _Sena Er: https://github.com/sena-neuro
.. _Senwen Deng: https://snwn.de
.. _Sergey Antopolskiy: https://github.com/antopolskiy
.. _Seth Bashford: https://github.com/sbashford
.. _Seyed Yahya Shirazi: https://neuromechanist.github.io
.. _Sharif Haason: https://github.com/sharifhsn
.. _Sheraz Khan: https://github.com/SherazKhan
.. _Shresth Keshari: https://github.com/shresth-keshari
.. _Shristi Baral: https://github.com/shristibaral
.. _Shruti Bhale: https://github.com/shruti423
.. _Silvia Cotroneo: https://github.com/sfc-neuro
.. _Simeon Wong: https://github.com/dtxe
.. _Simon Kern: https://skjerns.de
.. _Simon Kornblith: https://simonster.com
.. _Simon M. Hofmann: https://github.com/SHEscher
.. _Simon-Shlomo Poil: https://github.com/simon-shlomo
.. _Sina Esmaeili: https://github.com/snesmaeili
.. _Sondre Foslien: https://github.com/sondrfos
.. _Sophie Herbst: https://github.com/SophieHerbst
.. _Sourav Singh: https://github.com/souravsingh
.. _Srivarsha Chivukula: https://github.com/varshaa-1616
.. _Stanislas Chambon: https://github.com/Slasnista
.. _Stefan Appelhoff: https://stefanappelhoff.com
.. _Stefan Repplinger: https://github.com/stfnrpplngr
.. _Steinn Hauser Magnússon: https://github.com/steinnhauser
.. _Stephanie Jones: https://sites.brown.edu/stephanie-r-jones-lab/
.. _Steve Matindi: https://github.com/stevemats
.. _Steven Bethard: https://github.com/bethard
.. _Steven Bierer: https://github.com/neurolaunch
.. _Steven Gutstein: https://github.com/smgutstein
.. _Sumalyo Datta: https://github.com/Sumalyo
.. _Susanna Aro: https://www.linkedin.com/in/susanna-aro
.. _Svea Marie Meyer: https://github.com/SveaMeyer13
.. _sviter: https://github.com/sviter
.. _T. Wang: https://github.com/twang5
.. _Tal Linzen: https://tallinzen.net/
.. _Tamas Fehervari: https://github.com/zEdS15B3GCwq
.. _Tanay Gahlot: https://github.com/TanayGahlot
.. _Teemu Taivainen: https://github.com/ttaiv
.. _Teon Brooks: https://github.com/teonbrooks
.. _Tharupahan Jayawardana: https://github.com/tharu-jwd
.. _Théo Castillo: https://github.com/theosorus
.. _Théodore Papadopoulo: https://github.com/papadop
.. _Thomas A Caswell: https://tacaswell.github.io
.. _Thomas Binns: https://github.com/tsbinns
.. _Thomas Donoghue: https://github.com/TomDonoghue
.. _Thomas Grainger: https://github.com/graingert
.. _Thomas Hartmann: https://github.com/thht
.. _Thomas Jochmann: https://github.com/tjochmann
.. _Thomas Moreau: https://github.com/tomMoral
.. _Thomas Radman: https://github.com/tradman
.. _Tim Anderson: https://github.com/timothyanderson096-ocdealcheck
.. _Tim Gates: https://github.com/timgates42
.. _Timon Merk: https://github.com/timonmerk
.. _Timothy Gates: https://au.linkedin.com/in/tim-gates-0528a4199
.. _Timur Sokhin: https://github.com/Qwinpin
.. _Tod Flak: https://github.com/todflak
.. _Tom Dupré la Tour: https://github.com/TomDLT
.. _Tom Ma: https://github.com/myd7349
.. _Tom Stone: https://github.com/tomdstone
.. _Tommy Clausner: https://github.com/TommyClausner
.. _Toomas Erik Anijärv: https://github.com/teanijarv
.. _Tristan Stenner: https://github.com/tstenner/
.. _Tziona NessAiver: https://github.com/TzionaN
.. _user27182: https://github.com/user27182
.. _Valerii Chirkov: https://github.com/vagechirkov
.. _Varun Kasyap Pentamaraju: https://github.com/varunkasyap
.. _Velu Prabhakar Kumaravel: https://github.com/vpKumaravel
.. _Victor Férat: https://github.com/vferat
.. _Victoria Peterson: https://github.com/vpeterson
.. _Vincent Gao: https://github.com/gaoflow
.. _Virginie van Wassenhove: https://brainthemind.com/virginie-van-wassenhove
.. _Wei Xu: https://github.com/psyxw
.. _Will Turner: https://bootstrapbill.github.io
.. _Wouter Kroot: https://github.com/WouterKroot
.. _Xabier de Zuazo: https://github.com/zuazo
.. _Xiaokai Xia: https://github.com/dddd1007
.. _Yaroslav Halchenko: http://haxbylab.dartmouth.edu/ppl/yarik.html
.. _Yiping Zuo: https://github.com/frostime
.. _Yixiao Shen: https://github.com/SYXiao2002
.. _Young Truong: https://github.com/dungscout96
.. _Yousra Bekhti: https://www.linkedin.com/pub/yousra-bekhti/56/886/421
.. _Yu-Han Luo: https://github.com/yh-luo
.. _Zahra M. Aghajan: https://github.com/Zahra-M-Aghajan
.. _Zhi Zhang: https://github.com/tczhangzhi/
.. _Ziyi ZENG: https://github.com/ZiyiTsang
.. _Zvi Baratz: https://github.com/ZviBaratz
